version: '3.8'
services:
  backend:
    build: ./backend
    container_name: rl-ecommerce-backend
    ports:
      - "5001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: .
    container_name: rl-ecommerce-frontend
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
