services:
  backend:
    build: ./backend
    container_name: rl-ecommerce-backend
    ports:
      - "5001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/rl-ecommerce
    depends_on:
      - mongo

  frontend:
    build: .
    container_name: rl-ecommerce-frontend
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000/products
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: rl-ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
