name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version/tag (e.g., v1.0.0)'
        required: true
        default: 'latest'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build .
            --file Dockerfile
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/rl-ecommerce-frontend:${{ github.event.inputs.version || 'latest' }}

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rl-ecommerce-frontend:${{ github.event.inputs.version || 'latest' }}

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build ./backend
            --file ./backend/Dockerfile
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/rl-ecommerce-backend:${{ github.event.inputs.version || 'latest' }}

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rl-ecommerce-backend:${{ github.event.inputs.version || 'latest' }}
